export function $<T extends Element>(selector: string): T {
	const element = document.querySelector(selector);
	if (!element) throw new Error(`Missing element: ${selector}`);
	return element as unknown as T;
}

export type EditorRefs = ReturnType<typeof collectRefs>;

export function collectRefs() {
	return {
		canvas: $<HTMLCanvasElement>("#coverCanvas"),
		stage: $<HTMLDivElement>("#dropStage"),
		stageScroller: $<HTMLDivElement>("#stageScroller"),
		assetTray: $<HTMLDivElement>("#assetTray"),
		ratingsTray: $<HTMLDivElement>("#ratingsTray"),
		statusbar: $<HTMLDivElement>("#statusbar"),
		selectedLabel: $<HTMLElement>("#selectedLabel"),
		inspector: $<HTMLDivElement>("#inspector"),
		assetCount: $<HTMLElement>("#assetCount"),
		undoAction: $<HTMLButtonElement>("#undoAction"),
		redoAction: $<HTMLButtonElement>("#redoAction"),
		undoActionStage: $<HTMLButtonElement>("#undoActionStage"),
		redoActionStage: $<HTMLButtonElement>("#redoActionStage"),
		startTour: $<HTMLButtonElement>("#startTour"),
		startTourStage: $<HTMLButtonElement>("#startTourStage"),
		saveProject: $<HTMLButtonElement>("#saveProject"),
		loadProject: $<HTMLInputElement>("#loadProject"),
		exportPng: $<HTMLButtonElement>("#exportPng"),
		exportPdf: $<HTMLButtonElement>("#exportPdf"),
		addTitle: $<HTMLButtonElement>("#addTitle"),
		addTextButton: $<HTMLButtonElement>("#addText"),
		addBox: $<HTMLButtonElement>("#addBox"),
		imageUploadButton: $<HTMLButtonElement>("#imageUploadButton"),
		imageUpload: $<HTMLInputElement>("#imageUpload"),
		toggleGuides: $<HTMLInputElement>("#toggleGuides"),
		fitZoom: $<HTMLButtonElement>("#fitZoom"),
		textContent: $<HTMLTextAreaElement>("#textContent"),
		fontFamily: $<HTMLSelectElement>("#fontFamily"),
		fontSize: $<HTMLInputElement>("#fontSize"),
		fillColor: $<HTMLInputElement>("#fillColor"),
		opacity: $<HTMLInputElement>("#opacity"),
		rotation: $<HTMLInputElement>("#rotation"),
		textAlign: $<HTMLSelectElement>("#textAlign"),
		imageFit: $<HTMLSelectElement>("#imageFit"),
		replaceImage: $<HTMLButtonElement>("#replaceImage"),
		replaceImageInput: $<HTMLInputElement>("#replaceImageInput"),
		posX: $<HTMLInputElement>("#posX"),
		posY: $<HTMLInputElement>("#posY"),
		posW: $<HTMLInputElement>("#posW"),
		posH: $<HTMLInputElement>("#posH"),
		bringForward: $<HTMLButtonElement>("#bringForward"),
		sendBackward: $<HTMLButtonElement>("#sendBackward"),
		duplicateLayer: $<HTMLButtonElement>("#duplicateLayer"),
		deleteLayer: $<HTMLButtonElement>("#deleteLayer"),
		canvasDelete: $<HTMLButtonElement>("#canvasDelete"),
		selectionToolbar: $<HTMLDivElement>("#selectionToolbar"),
		quickAlign: $<HTMLButtonElement>("#quickAlign"),
		quickColor: $<HTMLInputElement>("#quickColor"),
		quickFit: $<HTMLButtonElement>("#quickFit"),
		quickBackward: $<HTMLButtonElement>("#quickBackward"),
		quickForward: $<HTMLButtonElement>("#quickForward"),
		quickDuplicate: $<HTMLButtonElement>("#quickDuplicate"),
		quickDelete: $<HTMLButtonElement>("#quickDelete"),
		tourOverlay: $<HTMLDivElement>("#tourOverlay"),
		tourSpotlight: $<HTMLDivElement>("#tourSpotlight"),
		tourCard: $<HTMLElement>("#tourCard"),
		tourMeta: $<HTMLDivElement>("#tourMeta"),
		tourTitle: $<HTMLHeadingElement>("#tourTitle"),
		tourBody: $<HTMLParagraphElement>("#tourBody"),
		tourSkip: $<HTMLButtonElement>("#tourSkip"),
		tourPrev: $<HTMLButtonElement>("#tourPrev"),
		tourNext: $<HTMLButtonElement>("#tourNext"),
		uiTooltip: $<HTMLDivElement>("#uiTooltip"),
	};
}
